### ISSUE TITLE
Is this repo provided under the terms of an open source license?

### ISSUE THREAD

**Issue by interstateone** [exyte/replicating#4]
Hey there! I was wondering if the contents of this repo were provided under a particular open source license? I see most of your other repos use MIT, so I wasn't sure if this repo not specifying one was intentional or not. Do you think you could clarify this by adding a LICENSE file or stating that all rights are reserved in the README?

Thanks for releasing these examples, and for taking the time to consider this. 😄

**Comment by zapletnev** [comment]
Hi @interstateone! Thanks for pointing! I have added the MIT license file.
